### PR TITLE
Redirect to home page if url provided is empty

### PR DESCRIPTION
**Pull request by spanagiot**
Flask crashes if url is empty so a check added to prevent this situation

### CODE REVIEW

**Comment by daknob** [comment]
What exactly crashes? Can you demonstrate the appropriate payload to cause a crash?

**Comment by spanagiot** [comment]
Click on "Shorten link" without providing a url

**Comment by daknob** [comment]
Correct. Are you sure your code fixes the issue?

Hmm. You are right. There seems to be a problem with the refactoring that causes this. Thanks!

**Comment by spanagiot** [comment]
In this specific situation, code expected that URL would be correct. So when it tries to generate a unique URL it concatenates 'str' and 'int' ('Invalid URL' and 400). With this patch, the simplest solution is provided, checking if one of these two exist before proceeding with the link generation

Unfortunately, this solution breaks API

**Comment by spanagiot** [comment]
Added proper json response that covers API issue.

**Comment by daknob** [comment]
This works indeed but it seems too hacky. I will try to come up with something so we can avoid a code refactor after this merge.. :-)

**Comment by daknob** [comment]
The issue has been resolved with commit 0e64e761a63e4acd1f2507e29352f0e00e1240bc in a more sophisticated way. Thanks for submitting this Pull Request as well as this bug!

**Pull request closed without merging**
